version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    # Porta padr達o do RabbitMQ
      - "15672:15672"  # Porta da interface web de gerenciamento
    environment:
      - RABBITMQ_DEFAULT_USER=admin      # Usuario padr達o
      - RABBITMQ_DEFAULT_PASS=admin123   # Senha padr達o
      - RABBITMQ_DEFAULT_VHOST=myvhost   # VHost padr達o
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  rabbitmq_data: 